apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: workflow-network-chaos
  namespace: hazelcast
spec:
  entry: workflow-parallel-flipflopandnetworkchaos
  templates:
    - name: workflow-parallel-flipflopandnetworkchaos
      templateType: Parallel
      deadline: 4h
      children:
        - workflow-network-intra-az-delay
        - workflow-network-dev3-delay
        - workflow-serial-flipflop
    - name: workflow-network-intra-az-delay
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'app.kubernetes.io/instance': 'dev'
            'app': 'bbclient'
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'app.kubernetes.io/instance': 'dev'
              'app': 'bbclient'
        delay:
          latency: '6ms'
          jitter: '0ms'
          correlation: '100'
    - name: workflow-network-dev3-delay
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
          labelSelectors:
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
        delay:
          latency: '30ms'
          correlation: '75'
          jitter: '20ms'
          reorder:
            gap: 1000
            reorder: '0.1'
            correlation: '90'
    - name: workflow-network-dev3-bandwidth
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: bandwidth
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
          labelSelectors:
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
        bandwidth:
          rate: '10mbps'
          limit: 209715200
          buffer: 100000
    - name: workflow-network-partition
      templateType: NetworkChaos
      deadline: 70s
      networkChaos:
        direction: both
        action: partition
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
    - name: workflow-network-suspend
      templateType: Suspend
      deadline: 60s
    - name: workflow-serial-flipflop
      templateType: Serial
      deadline: 4h
      children:
        - workflow-network-partition
        - workflow-network-suspend
