apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{NodeRoleARN}}
      username: system:node:{{ "{{" }}EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
