apiVersion: v1
kind: Service
metadata:
  name: bbclient
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  type: LoadBalancer
  selector:
    app: bbclient
  ports:
    - port: 4000
      targetPort: 4000
