apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hazelcast-client-priclass
value: -1000000
globalDefault: false
description: "This priority class should be used for Hz clients only."
