apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: workflow-network-chaos
  namespace: hazelcast
spec:
  entry: workflow-parallel-flipflopandnetworkchaos
  templates:
    - name: workflow-parallel-flipflopandnetworkchaos
      templateType: Parallel
      deadline: 4h
      children:
        - workflow-network-intra-az-delay-0-to-1
        - workflow-network-intra-az-delay-01-to-2
        - workflow-serial-flipflop
          #        - workflow-network-dev3-delay
    - name: workflow-network-intra-az-delay-0-to-1
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '0'
          labelSelectors:
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '1'
        delay:
          latency: '2ms'
          jitter: '1ms'
          correlation: '75'
    - name: workflow-network-intra-az-delay-01-to-2
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
          labelSelectors:
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
        delay:
          latency: '8ms'
          jitter: '1ms'
          correlation: '75'
    - name: workflow-network-dev3-delay
      templateType: NetworkChaos
      deadline: 4h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
          labelSelectors:
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
        delay:
          latency: '15ms'
          jitter: '5ms'
          correlation: '90'
            #          reorder:
            #            gap: 1000
            #            reorder: '0.1'
            #            correlation: '90'
    - name: workflow-serial-flipflop
      templateType: Serial
      deadline: 4h
      children:
        - workflow-network-partition
        - workflow-network-suspend
    - name: workflow-network-partition
      templateType: NetworkChaos
      deadline: 70s
      networkChaos:
        direction: both
        action: partition
        mode: all
        selector:
          namespaces:
            - hazelcast
          labelSelectors:
            'apps.kubernetes.io/pod-index': '2'
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            labelSelectors:
              'apps.kubernetes.io/pod-index': '0'
              'apps.kubernetes.io/pod-index': '1'
    - name: workflow-network-suspend
      templateType: Suspend
      deadline: 60s
