apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: workflow-splitdelay
  namespace: hazelcast
spec:
  entry: workflow-splitdelay-pl
  templates:
    - name: workflow-splitdelay-pl
      templateType: Parallel
      deadline: 28m
      children:
        - workflow-splitdelay-dev3-delay
        - workflow-splitdelay-sl-flipflop
    - name: workflow-splitdelay-dev3-delay
      templateType: NetworkChaos
      deadline: 2h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          expressionSelectors:
            - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
            - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['2'] }
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            expressionSelectors:
              - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
              - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['0', '1'] }
        delay:
          latency: '15ms'
          jitter: '5ms'
          correlation: '75'
            #          reorder:
            #            gap: 1000
            #            reorder: '0.1'
            #            correlation: '90'
    - name: workflow-splitdelay-sl-flipflop
      templateType: NetworkChaos
      deadline: 2h
      networkChaos:
        direction: both
        action: partition
        mode: all
        selector:
          namespaces:
            - hazelcast
          expressionSelectors:
            - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
            - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['2'] }
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            expressionSelectors:
              - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
              - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['0', '1'] }
