apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: workflow-baselatency
  namespace: hazelcast
spec:
  entry: workflow-baselatency-pl-01-and-01to2
  templates:
    - name: workflow-baselatency-pl-01-and-01to2
      templateType: Parallel
      deadline: 4h
      children:
        - workflow-baselatency-intra-az-delay-0-to-1
        - workflow-baselatency-intra-az-delay-01-to-2
    - name: workflow-baselatency-intra-az-delay-0-to-1
      templateType: NetworkChaos
      deadline: 2h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          expressionSelectors:
            - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
            - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['0'] }
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            expressionSelectors:
              - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
              - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['1'] }
        delay:
          latency: '2ms'
          jitter: '1ms'
          correlation: '75'
    - name: workflow-baselatency-intra-az-delay-01-to-2
      templateType: NetworkChaos
      deadline: 2h
      networkChaos:
        direction: both
        action: delay
        mode: all
        selector:
          namespaces:
            - hazelcast
          expressionSelectors:
            - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
            - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['2'] }
        target:
          mode: all
          selector:
            namespaces:
              - hazelcast
            expressionSelectors:
              - { key: 'app.kubernetes.io/instance', operator: In, values: ['dev'] }
              - { key: 'apps.kubernetes.io/pod-index', operator: In, values: ['0', '1'] }
        delay:
          latency: '8ms'
          jitter: '1ms'
          correlation: '75'
