apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{SrvNmCluster}}
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: {{AppVersion}}
  licenseKeySecretName: license
  clusterSize: {{HzMemberCount}}
  clusterName: {{SrvNmCluster}}
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
    memberAccess: NodePortNodeName
  jvm:
    args:
      - "-Dcom.sun.management.jmxremote"
      - "-Dcom.sun.management.jmxremote.authenticate=false"
  properties:
    "hazelcast.partition.count": "29"
    "hazelcast.jmx": "true"
