apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{SrvNmCluster}}
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: {{AppVersion}}
  licenseKeySecretName: license
  clusterSize: {{HzNodeCount}}
  clusterName: {{SrvNmCluster}}
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
    memberAccess: LoadBalancer
