apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{SrvNmCluster}}
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: {{AppVersion}}
  licenseKeySecretName: license
  clusterSize: {{HzMemberCount}}
  clusterName: {{SrvNmCluster}}
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
    memberAccess: NodePortNodeName
  properties:
    "hazelcast.socket.send.buffer.size": "2048"
    "hazelcast.socket.receive.buffer.size": "2048"
  jvm:
    args:
      - "-Dcom.sun.management.jmxremote"
      - "-Dcom.sun.management.jmxremote.authenticate=false"
    memory:
      initialRAMPercentage: "38"
      maxRAMPercentage: "38"
      minRAMPercentage: "38"
