apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{SrvNmCluster}}
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: {{AppVersion}}
  licenseKeySecretName: license
  clusterSize: {{HzMemberCount}}
  clusterName: {{SrvNmCluster}}
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
    memberAccess: NodePortNodeName
  highAvailabilityMode: ZONE
  properties:
    "hazelcast.cluster.version.auto.upgrade.enabled": "false"
      #    "hazelcast.invocation.max.retry.count": "10"
