apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: cluster
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '5.3.6'
  licenseKeySecretName: license
  clusterSize: {{NodeCount}}
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
