apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{SrvNmCluster}}
spec:
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: {{AppVersion}}
  licenseKeySecretName: license
  clusterSize: {{HzMemberCount}}
  clusterName: {{SrvNmCluster}}
  highAvailabilityMode: ZONE
  properties:
    "hazelcast.invocation.max.retry.count": "10"
    "hazelcast.diagnostics.enabled": "true"
    "hazelcast.diagnostics.stdout": "STDOUT"
    "hazelcast.diagnostics.metric.level": "info"
    "hazelcast.diagnostics.invocation.sample.period.seconds": "30"
    "hazelcast.diagnostics.pending.invocations.period.seconds": "30"
    "hazelcast.diagnostics.slowoperations.period.seconds": "30"
    "hazelcast.diagnostics.storeLatency.period.seconds": "60"
  scheduling:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - dev
              topologyKey: kubernetes.io/hostname
