apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: {{SrvNmManctr}}
spec:
  licenseKeySecretName: license
  repository: 'hazelcast/management-center'
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
    - address: {{SrvNmCluster}}
      name: {{SrvNmCluster}}
