apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: {{SrvNmManctr}}
spec:
  licenseKeySecretName: license
  repository: 'hazelcast/management-center'
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
    - address: {{SrvNmCluster}}
      name: {{SrvNmCluster}}
  jvm:
    args:
      - "-Dhazelcast.mc.rest.enabled=true"
  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "2"
  scheduling:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - hazelcast
            topologyKey: kubernetes.io/hostname
